sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cc@981208
  alioss:
    endpoint: oss-ap-southeast-1.aliyuncs.com
    access-key-id: LTAI5tRg62wudkm4twY9fLRa
    access-key-secret: FZfuIFlKnfYryJ5UxgEN5DPqaUcxwy
    bucket-name: sky-itcast-geer
  redis:
    host: localhost
    password: Cc@981208
    port: 6379
    database: 10